export const CHANGE_BLOGMENU_ACTIVENAME = "CHANGE_BLOGMENU_ACTIVENAME";
export const CHANGE_PLAYSTATUS = "CHANGE_PLAYSTATUS";
export const INITIAL_SONGLISTS = "INITIAL_SONGLISTS";
export const GET_SONGLISTS = "GET_SONGLISTS";

